name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

concurrency:
  group: release

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: spotdemo4/better-checkout@a08be04e9f594479a4ac25b1a67d707190dd619e # v0.10.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          fetch-depth: 0

      - name: Bump
        uses: spotdemo4/bumper@58f7b1f61e95f4a92b3cc1a27454fd220ce00d9c # v0.14.7
        with:
          debug: ${{ runner.debug }}
          force: ${{ inputs.force }}
          files: |-
            action.yaml
            .github/README.md
