name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@91bbca32bfa8d48baf47c8b2c0a15ce89c5ff0aa # v1.42.0

      - name: Check
        run: nix flake check

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: spotdemo4/better-checkout@87336d3542f856e09b06c19d4bc470325776e6e3 # v0.9.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          fetch-depth: 0

      - name: Release
        uses: spotdemo4/flake-release@7640bfccc63c2e2540211a5d48667138d70ff4e6 # v0.14.3
        with:
          github_token: ${{ steps.checkout.outputs.token }}
          packages: |
            images.x86_64-linux.default
