name: update

on:
  schedule:
    - cron: "0 7-13 * * *" # once an hour from 07:00 to 13:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@b0b33f024c18fa92f42f732e2e2001de507210cd # v1.45.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          shell: update

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .github/renovate.json
          RENOVATE_TOKEN: ${{ steps.init.outputs.token }}
        run: renovate
